version: '3.7'
services:
  db:
    container_name: pgvector
    image: ankane/pgvector
    ports:
     - 5432:5432
    environment:
      - POSTGRES_DB=rag_storage_tenant_test
      - POSTGRES_USER=tenant_test
      - POSTGRES_PASSWORD=tenant_test
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
     - ./init_local.sql:/docker-entrypoint-initdb.d/init.sql