version: '3.7'
services:
  db:
    container_name: pgvector
    image: ankane/pgvector
    ports:
     - 5433:5432
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_usr
      - POSTGRES_PASSWORD=postgres_pwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: ["postgres", "-c", "log_statement=all"]